/*
    Lang.swift is part of Appudo

    Copyright (C) 2015-2016
        6407b027e25c10f021c78bea3eeaa9b6ea318834c74b1daad29420aa2352003c source@appudo.com

    Licensed under the Apache License, Version 2.0

    See http://www.apache.org/licenses/LICENSE-2.0 for more information
*/

/**
Lang contains possible values for user languages.

-- SeeAlso: User
*/
public enum Lang : Int32 {
       case AA
       case AB
       case AE
       case AF
       case AK
       case AM
       case AN
       case AR
       case AS
       case AV
       case AY
       case AZ
       case BA
       case BE
       case BG
       case BH
       case BI
       case BM
       case BN
       case BO
       case BR
       case BS
       case CA
       case CE
       case CH
       case CO
       case CR
       case CS
       case CU
       case CV
       case CY
       case DA
       case DE
       case DV
       case DZ
       case EE
       case EL
       case EN
       case EO
       case ES
       case ET
       case EU
       case FA
       case FF
       case FI
       case FJ
       case FO
       case FR
       case FY
       case GA
       case GD
       case GL
       case GN
       case GU
       case GV
       case HA
       case HE
       case HI
       case HO
       case HR
       case HT
       case HU
       case HY
       case HZ
       case IA
       case ID
       case IE
       case IG
       case II
       case IK
       case IN
       case IO
       case IS
       case IT
       case IU
       case IW
       case JA
       case JI
       case JV
       case JW
       case KA
       case KG
       case KI
       case KJ
       case KK
       case KL
       case KM
       case KN
       case KO
       case KR
       case KS
       case KU
       case KV
       case KW
       case KY
       case LA
       case LB
       case LG
       case LI
       case LN
       case LO
       case LT
       case LU
       case LV
       case MG
       case MH
       case MI
       case MK
       case ML
       case MN
       case MO
       case MR
       case MS
       case MT
       case MY
       case NA
       case NB
       case ND
       case NE
       case NG
       case NL
       case NN
       case NO
       case NR
       case NV
       case NY
       case OC
       case OJ
       case OM
       case OR
       case OS
       case PA
       case PI
       case PL
       case PS
       case PT
       case QU
       case RM
       case RN
       case RO
       case RU
       case RW
       case SA
       case SC
       case SD
       case SE
       case SG
       case SH
       case SI
       case SK
       case SL
       case SM
       case SN
       case SO
       case SQ
       case SR
       case SS
       case ST
       case SU
       case SV
       case SW
       case TA
       case TE
       case TG
       case TH
       case TI
       case TK
       case TL
       case TN
       case TO
       case TR
       case TS
       case TT
       case TW
       case TY
       case UG
       case UK
       case UR
       case UZ
       case VE
       case VI
       case VO
       case WA
       case WO
       case XH
       case YI
       case YO
       case ZA
       case ZH
       case ZU
       case AR_AE
       case AR_BH
       case AR_DZ
       case AR_EG
       case AR_IQ
       case AR_JO
       case AR_KW
       case AR_LB
       case AR_LY
       case AR_MA
       case AR_OM
       case AR_QA
       case AR_SA
       case AR_SY
       case AR_TN
       case AR_YE
       case DE_AT
       case DE_CH
       case DE_LI
       case DE_LU
       case EN_AU
       case EN_BZ
       case EN_CA
       case EN_GB
       case EN_IE
       case EN_JM
       case EN_NZ
       case EN_TT
       case EN_US
       case EN_ZA
       case ES_AR
       case ES_BO
       case ES_CL
       case ES_CO
       case ES_CR
       case ES_DO
       case ES_EC
       case ES_GT
       case ES_HN
       case ES_MX
       case ES_NI
       case ES_PA
       case ES_PE
       case ES_PR
       case ES_PY
       case ES_SV
       case ES_UY
       case ES_VE
       case FR_BE
       case FR_CA
       case FR_CH
       case FR_LU
       case IT_CH
       case NL_BE
       case PT_BR
       case RO_MD
       case RU_MD
       case SV_FI
       case ZH_CN
       case ZH_HK
       case ZH_SG
       case ZH_TW
}
